export const Book = {
  booksStore: [
    {
      id: 1,
      title: "Bring Your Human to Work",
      author: "Erica Keswin",
      image: "../../../assets/humanWork.jpg",
      timeToRead: "13-minute read",
      numberOfReads: "1.9k reads",
      isFinished: false,
      isReading: true,
    },
    {
      id: 2,
      title: "Employee to Entrepreneur",
      author: "Steve Glaveski",
      image: "../../../assets/employee.jpg",
      timeToRead: "14-minute read",
      numberOfReads: "1.9k reads",
      isFinished: true,
      isReading: false,
    },
    {
      id: 3,
      title: "Doesn't Hurt to Ask",
      author: "Trey Gowdy",
      image: "../../../assets/doesntHurtToAsk.jpg",
      timeToRead: "15-minute read",
      numberOfReads: "1k reads",
      isFinished: false,
      isReading: true,
    },
    {
      id: 4,
      title: "The Fate of Food",
      author: "Amanda Little",
      image: "../../../assets/theFateOfFood.jpg",
      timeToRead: "12-minute read",
      numberOfReads: "16k reads",
      isFinished: false,
      isReading: true,
    },
    {
      id: 5,
      title: "Lives of the Stoics",
      author: "Ryan Holiday, Stephen Hansel",
      timeToRead: "13-minute read",
      numberOfReads: "19k reads",
      image: "../../../assets/livesOfStoics.jpg",
      isFinished: false,
      isReading: true,
    },
    {
      id: 6,
      title: "Loving Your Business",
      author: "Debbie King",
      timeToRead: "13-minute read",
      numberOfReads: "9k reads",
      image: "../../../assets/lovingYourBusiness.jpg",
      isFinished: true,
      isReading: false,
    },
    {
      id: 7,
      title: "The Lonely Century",
      author: "Noreena Hertz",
      timeToRead: "15-minute read",
      numberOfReads: "8.1k reads",
      image: "../../../assets/theLonelyCentury.jpg",
      isFinished: true,
      isReading: false,
    },
    {
      id: 8,
      title: "Eat Better,Feel Better",
      author: "Giada De Laurentiis",
      timeToRead: "13-minute read",
      numberOfReads: "1.9k reads",
      image: "../../../assets/eatBetterFeelBetter.jpg",
      isFinished: false,
      isReading: true,
    },
    {
      id: 9,
      title: "Dropshipping",
      author: "James Moore",
      timeToRead: "12-minute read",
      numberOfReads: "10k reads",
      image: "../../../assets/dropshipping.jpg",
      isFinished: true,
      isReading: false,
    },
    {
      id: 10,
      title: "Beyond Entrepreneurship",
      author: "Jim Collins & Bill Lazier",
      timeToRead: "13-minute read",
      numberOfReads: "1.9k reads",
      image: "../../../assets/beyond.jpg",
      isFinished: true,
      isReading: false,
    },
    {
      id: 11,
      title: "Being Boss",
      author: "Kathleen Shannon Land Emily",
      timeToRead: "13-minute read",
      numberOfReads: "21k reads",
      image: "../../../assets/beingBoss.jpg",
      isFinished: false,
      isReading: true,
    },
  ],
};
